#!/usr/bin/env python3
"""Compile an HLSL shader (shader model 3) into a C header, replacing Visual Studio's fxc step (PROJECT.md §5.3).

1. preprocess with clang's standard C preprocessor (vkd3d's own preprocessor does not expand nested macro
   arguments the way upstream's register macros need)
2. compile with vkd3d-compiler to legacy Direct3D bytecode (d3dbc)
3. emit `const unsigned char <var>[] = {...};`, the same shape fxc's /Fh output has (BYTE is unsigned char)

Usage: python3 -I compile_shader.py <src.hlsl> <profile, e.g. vs_3_0> <variable name> <out.h>
"""
import subprocess
import sys
import tempfile
from pathlib import Path


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    src, profile, var, out = Path(sys.argv[1]), sys.argv[2], sys.argv[3], Path(sys.argv[4])
    with tempfile.TemporaryDirectory() as tmp:
        pre, blob = Path(tmp) / "pre.hlsl", Path(tmp) / "shader.bin"
        subprocess.run(["clang", "-E", "-P", "-undef", "-x", "c", f"-I{src.parent}", str(src), "-o", str(pre)], check=True)
        subprocess.run(["vkd3d-compiler", "-x", "hlsl", "-b", "d3dbc", "-p", profile, "-e", "main", str(pre),
                        "-o", str(blob)], check=True)
        code = blob.read_bytes()
    if not code:
        sys.exit(f"compile_shader: empty output for {src}")
    lines = [", ".join(f"0x{b:02x}" for b in code[i:i + 16]) for i in range(0, len(code), 16)]
    body = ",\n    ".join(lines)
    text = (f"// GENERATED by Scripts/indy/compile_shader.py from {src.name} ({profile}, vkd3d-compiler). Do not edit.\n"
            f"const unsigned char {var}[] =\n{{\n    {body}\n}};\n")
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)


if __name__ == "__main__":
    main()
