#!/usr/bin/env python3
"""Generate the one translation unit that emits external definitions for upstream's header `inline` functions.

MSVC compiles a plain C `inline` function like C++ does: every file that needs it gets a mergeable copy.
Standard C (C99 and later) emits no standalone copy at all unless one translation unit also declares the
function `extern`. Calls that are not inlined (all of them in debug builds) then end up as undefined symbols.
This script finds every non-static `inline` function defined in upstream headers and writes a C file that
includes those headers and redeclares each function `extern`. That file supplies the single external
definition, without editing upstream code. PROJECT.md §5.3.

Usage: python3 -I gen_inline_externals.py <repo root> <out.c>
"""
import re
import sys
from pathlib import Path

DEFINITION = re.compile(r"^inline\s+[^;{(]*?\b(\w+)\s*\(")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    root, out = Path(sys.argv[1]), Path(sys.argv[2])
    found = []  # (include path, function)
    for hdr in sorted(list(root.glob("Libs/**/*.h")) + list(root.glob("Jones3D/**/*.h"))):
        if "external" in hdr.parts or "RTI" in hdr.parts:
            continue
        inc = hdr.relative_to(root / "Libs") if hdr.is_relative_to(root / "Libs") else hdr.relative_to(root)
        for line in hdr.read_text("latin1").splitlines():
            code = line.split("//", 1)[0].rstrip()
            m = DEFINITION.match(code)
            if m and not code.endswith(";"):
                found.append((inc.as_posix(), m.group(1)))

    lines = ["// GENERATED by Scripts/indy/gen_inline_externals.py. Do not edit.",
             "// External definitions for upstream's header inline functions (C99 inline semantics).",
             "// Some upstream headers are not self-contained: include what their .c files include first.",
             "#include <j3dcore/j3d.h>", "#include <commdlg.h>",
             "#include <std/types.h>", "#include <rdroid/types.h>", "#include <sound/types.h>",
             "#include <sound/Driver.h>", "#include <sith/types.h>", "#include <wkernel/types.h>",
             "#include <Jones3D/types.h>"]
    lines += [f"#include <{inc}>" for inc in dict.fromkeys(inc for inc, _ in found)]
    lines += [""] + [f"extern __typeof__({fn}) {fn};" for _, fn in found]
    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    print(f"gen_inline_externals: {len(found)} header inline functions")


if __name__ == "__main__":
    main()
