#!/usr/bin/env python3
"""Generate v1.2 copies of upstream's address headers from the address map (PROJECT.md §5.7).

Every upstream header with `#define <name>_ADDR 0x...` (each module's RTI/addresses.h, plus smush/SmushPlay.h)
is copied to <outdir> with the same include path, and its addresses are replaced:
  functions  verified -> v1.2 address; anything else -> 0, which the patched J3DHookFunction() skips
  data       v1.2 address
  EXE_*      section bounds of the host exe
Trampolines and live globals must be verified; otherwise generation fails. The build puts <outdir> before
Libs/ on the include path, so upstream code picks up these copies without being edited.

Usage: python3 -I gen_rti_headers.py <repo root> <rti_v12.csv> <host exe> <outdir>
"""
import csv
import os
import re
import struct
import sys
from pathlib import Path


def exe_bounds(path):
    data = Path(path).read_bytes()
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    nsec = struct.unpack_from("<H", data, pe + 6)[0]
    optsize = struct.unpack_from("<H", data, pe + 20)[0]
    opt = pe + 24
    image_base = struct.unpack_from("<I", data, opt + 28)[0]
    iat_rva, iat_size = struct.unpack_from("<II", data, opt + 96 + 8 * 12)
    secs = {}
    for i in range(nsec):
        off = opt + optsize + i * 40
        name = data[off:off + 8].rstrip(b"\0").decode("latin1")
        vsize, va = struct.unpack_from("<II", data, off + 8)
        secs[name] = (image_base + va, vsize)

    def end(name):
        va, vsize = secs[name]
        return (va + vsize + 0xFFF) & ~0xFFF

    rdata_start = secs[".rdata"][0]
    iat = image_base + iat_rva
    if iat == rdata_start:  # the import address table opens .rdata; upstream's range starts after it
        rdata_start = iat + iat_size
    return {
        "EXE_TEXT_START": secs[".text"][0], "EXE_TEXT_END": end(".text"),
        "EXE_RDATA_START": rdata_start, "EXE_RDATA_END": end(".rdata"),
    }


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    root, csv_path, exe, outdir = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3], Path(sys.argv[4])
    rows = {r["name"]: r for r in csv.DictReader(csv_path.open())}
    bounds = exe_bounds(exe)

    headers = sorted(root.glob("Libs/*/RTI/addresses.h")) + [root / "Jones3D/RTI/addresses.h", root / "Libs/smush/SmushPlay.h"]
    define = re.compile(r"^(#define\s+)(\w+)_ADDR(\s+)(0x[0-9A-Fa-f]+)(.*)$", re.M)
    disabled, errors, count, written = [], [], 0, 0
    skipped_unreachable = []

    for hdr in headers:
        rel = hdr.relative_to(root / "Libs") if hdr.is_relative_to(root / "Libs") else hdr.relative_to(root)

        def replace(m):
            nonlocal count
            name = m.group(2)
            if name in bounds:
                new = bounds[name]
            elif name not in rows:
                errors.append(f"{name}: not in the address map")
                return m.group(0)
            else:
                r = rows[name]
                critical = "trampoline" in r["usage"] or "live" in r["usage"]
                if critical and r["confidence"] != "verified":
                    errors.append(f"{name}: runtime-critical but {r['confidence']}")
                weak_unreachable = (r["kind"] == "func" and "hook" in r["usage"] and "trampoline" not in r["usage"]
                                    and r.get("evidence") == "weak" and r.get("reach") == "no"
                                    # opt-in only: the reachability scan is incomplete (leaving these hooks out
                                    # broke startup on 2026-10-06), so by default every verified hook is kept
                                    and os.environ.get("INDY_SKIP_WEAK_UNREACHABLE") == "1")
                if r["kind"] == "func" and r["confidence"] != "verified":
                    disabled.append(name)
                    new = 0
                elif weak_unreachable:
                    # nothing original can call it, so the hook gains nothing; a wrong address would patch a jump
                    # into some other function: leave it unhooked
                    skipped_unreachable.append(name)
                    new = 0
                else:
                    new = int(r["v12"], 16) if r["v12"] else 0
            count += 1
            return f"{m.group(1)}{name}_ADDR{m.group(3)}0x{new:08X}{m.group(5)}"

        text = define.sub(replace, hdr.read_text("latin1"))
        banner = f"// GENERATED by Scripts/indy/gen_rti_headers.py from {hdr.relative_to(root)} for Indy3D.exe v1.2. Do not edit.\n"
        out = outdir / rel
        content = banner + text
        if not out.exists() or out.read_text("latin1") != content:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content, "latin1")
            written += 1

    if errors:
        sys.exit("gen_rti_headers: " + "; ".join(errors))
    print(f"gen_rti_headers: {len(headers)} headers ({written} updated), {count} addresses; "
          f"{len(disabled)} unverified hooks disabled: {', '.join(sorted(disabled))}; "
          f"{len(skipped_unreachable)} weakly evidenced hooks left out because nothing original can reach them")


if __name__ == "__main__":
    main()
